### ISSUE TITLE
Save the row with missing email

### ISSUE THREAD

**Issue by Mte90** [CodeAtCode/CSVEmailVerifier#1]
Maybe in a new file

**Comment by anshuman73** [comment]
Can you give an example here of what you're trying to achieve ?
Perhaps an example input / example file and the thus problem you'd like to eradicate ?

**Comment by Mte90** [comment]
An example of csv https://github.com/CodeAtCode/CSVEmailVerifier/wiki/CSV-Example

**Comment by Mte90** [comment]
As you can see emailahoy say that domain.tld exist but is wrong, probably emailahoy is outdated (i am waiting for 2 pr like an year)

**Comment by triptu** [comment]
Hey can you give me an example of csv with missing email?

**Comment by Mte90** [comment]
https://github.com/CodeAtCode/CSVEmailVerifier/wiki/CSV-Example

**Comment by triptu** [comment]
The code(after my update) gives the expected answer. 
![new](https://cloud.githubusercontent.com/assets/16299282/19226911/86ad5210-8ecf-11e6-8778-a5cdb8890337.JPG)
What do you mean by missing email. I thought it means a row without the email column but in the example you sent both the rows contain email. Am I getting something wrong?

**Comment by Mte90** [comment]
I don't understand, can you explain better?

**Comment by triptu** [comment]
Actually I am unable to understand what's the issue here.  The title of the issue as written by you is, "Save the row with missing email". The sample test case you provided is working as expected.
Could you please explain me what new feature you want with a sample case?

**Comment by Mte90** [comment]
If you put a line in the csv without the email column in the file output that row is missing

**Comment by jlax47** [comment]
#7 Just created a pull request which adds support for rows with a blank/missing email column.

```
CSVEmailVerifier 1.0 by Mte90 for Codeat - https://github.com/CodeAtCode
Evaluating in progress...
 Email 1 mte90net@gmail.com exists!
 Email 2 fakeuser@domain.tld not exists!
 Email 3 is empty!
Check in the same path of the input file for the 'correct.test.csv', 'wrong.test.csv', and 'missing.test.csv' output files.
Processed 3 emails in 1 second.
```
