### ISSUE TITLE
check if email domain exist

### ISSUE THREAD

**Issue by Mte90** [CodeAtCode/CSVEmailVerifier#2]
Maybe with a ping

**Comment by kokomaster** [comment]
hello sir,
i test it for my friend email but said not exist!
did i missed something?

**Comment by Mte90** [comment]
open a ticket with the email, without that for me is impossible do define that but is not accurate at 100% this depends from the servers of the email.

**Comment by anshuman73** [comment]
@Mte90 Hi, you already seem to have a verification system with the emailhoy module. Doesn't it ping the domain as well ?
is what you are proposing something different than that ?
Can you please elaborate ?

**Comment by Mte90** [comment]
The problem is that he ping start a connection with the server but the domain of the email cannot exist.
Because the check of emailhoy is not 100% true will be useful to have also this information

**Comment by anshuman73** [comment]
So, would checking for an MX record be an approach you'd suggest ?

**Comment by Mte90** [comment]
I think something like that

**Comment by anshuman73** [comment]
Hi, I think I may have found something good for this. But it _largely depends on whether you'd like to have dependencies in the project or not._
This may be the solution to the problem - https://github.com/syrusakbary/validate_email
It can check the existence of the SMTP server and also if the email id itself exists or not.
Only issue, like I mentioned before, is that it has dependencies...

**Comment by Mte90** [comment]
Is not important so much the dependecis, the importat that works.
I know that emailahoy do few check with telnet to get toher information so a combo with this and with emailahoy can contain many information that enable us to check if the email is real.
Actually if you use the test data you can see that for him test@domain.tld exist.

**Comment by anshuman73** [comment]
him referring to emailahoy or the module I mentioned ?
Because, with validate_email module, it gives the invalid as the answer.

This module gives enough details too, if you want I'll have a look at the combo of emailahoy and this, but I'd prefer only this(validate_email) script to avoid complexity

This module(validate_email) seems to have some problems, like the timeout on some valid custom emails is a bit less and a nonetype is returned instead of false even when error message prints it doesn't exist (for example on gmail) (Attached screens); So, I will probably change this and make a slightly customized script

![screen](https://cloud.githubusercontent.com/assets/12889549/19017241/b9f9b80a-8850-11e6-9152-f034709a318e.jpg)

**Comment by Mte90** [comment]
I think that this is useful as first check but emailahoy do more sofisticated check so it's important to have it.
Maybe will be useful to have the script multithread to improve the check but I have no experience of that.

**Comment by anshuman73** [comment]
Hi again, I finally had the chance to look at emailhoy's source.
it seems that emailhoy does the exact thing that the validate email module i suggested - checks for mx record, sends a ping to smtp servers and returns output based on http codes. What's wrong with that ?

**Comment by anshuman73** [comment]
ahh, the emailhoy doesn't seem to be a package in the pypi anymore...
What do you suggest finally ? Using emailhoy can be troublesome without pip
![capture](https://cloud.githubusercontent.com/assets/12889549/19131217/2aad4dbe-8b6c-11e6-8f00-768fac25f941.JPG)

**Comment by Mte90** [comment]
If emailhoy is not anymore on pip the project need an alternative, so if your package is complete as feature of emailhoy (as I can remeber the project had support for specific mail server) it's time to migrate

**Comment by anshuman73** [comment]
Hmm, true. Emailhoy could check a specific email server. whereas this doesn't.
Should I migrate ?
Also, sorry for the late reply, I'm running a bit busy..

**Comment by Mte90** [comment]
I need a complete alternative to emailhoy for a migration so maybe a fork is the best solution with the implementation of new features, and next migrate.

**Comment by triptu** [comment]
@anshuman73 emailahoy is on pypi. You have used 'pip install emailhoy' instead of 'pip install python-emailahoy' which is correct.

**Comment by triptu** [comment]
emailahoy was not working for me. It was giving false results for many domains. I checked for alternatives. validate_email suggested by anshuman was updated 5 years ago last time and seems to be outdated. It too din't work right for me. I changed the dependency to Python-email-validator [https://github.com/JoshData/python-email-validator] which is well-maintained package and works fine.
